export const siteConfig = {
    name: "Paired",
    description: "Find the perfect room and roommate for you. ",
    navItems: [
        // {
        //     label: "Home",
        //     href: "/",
        // },
        {
            label: "Rooms",
            href: "/rooms",
        },
        {
            label: "Roommates",
            href: "/roommates",
        },
        // {
        //     label: "Blog",
        //     href: "/blog",
        // },
        {
            label: "About",
            href: "/about",
        },
    ],
    navMenuItems: [
        // {
        //     label: "Home",
        //     href: "/",
        // },
        {
            label: "Rooms",
            href: "/rooms",
        },
        {
            label: "Roommates",
            href: "/roommates",
        },
        // {
        //     label: "Blog",
        //     href: "/blog",
        // },
        {
            label: "About",
            href: "/about",
        },
        {
            label: "Logout",
            href: "/logout",
        },
    ],
    links: {
        github: "https://github.com/nextui-org/nextui",
        twitter: "https://twitter.com/getnextui",
        // docs: "https://nextui.org",
        // discord: "https://discord.gg/9b6yyZKmH4",
        // sponsor: "https://patreon.com/jrgarciadev",
    },
    propertyType: [
        "Flat / Apartment",
        "House",
        "Land",
        "Comercial Property",
        "Event centre / Venue",
    ],
    budget: [
        100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000,
        1000000, 2000000, 3000000, 5000000, 10000000, 20000000, 40000000,
        60000000, 80000000, 100000000,
    ],
    nigerianStates: [
        "Abia",
        "Adamawa",
        "Akwa Ibom ",
        "Anambra",
        "Bauchi",
        "Bayelsa ",
        "Benue",
        "Borno",
        "Cross River",
        "Delta",
        "Ebonyi",
        "Edo",
        "Ekiti",
        "Enugu",
        "Gombe",
        "Imo",
        "Jigawa",
        "Kaduna",
        "Kano",
        "Katsina",
        "Kebbi",
        "Kogi",
        "Kwara",
        "Lagos",
        "Nasarawa",
        "Niger",
        "Ogun ",
        "Ondo ",
        "Osun",
        "Oyo",
        "Plateau",
        "Rivers",
        "Sokoto",
        "Taraba",
        "Yobe",
        "Zamfara",
    ],
}
